author: Philip Niedertscheider
author_url: https://www.github.com/philprime
github_url: https://www.github.com/techprimate/TPPDF
root_url: https://techprimate.github.io/TPPDF/
module: TPPDF
output: docs
theme: fullwidth
xcodebuild_arguments: [-project, 'Example macOS/Example_macOS-SPM.xcodeproj', -scheme, 'Example macOS (SPM)']
